export interface NationalityOption {
  code: string;
  flag: string;
  label: string;
}

export const NATIONALITIES: NationalityOption[] = [
  { code: "CM", flag: "🇨🇲", label: "Camerounaise" },
  { code: "SN", flag: "🇸🇳", label: "Sénégalaise" },
  { code: "CI", flag: "🇨🇮", label: "Ivoirienne" },
  { code: "ML", flag: "🇲🇱", label: "Malienne" },
  { code: "GN", flag: "🇬🇳", label: "Guinéenne" },
  { code: "BF", flag: "🇧🇫", label: "Burkinabè" },
  { code: "TD", flag: "🇹🇩", label: "Tchadienne" },
  { code: "GA", flag: "🇬🇦", label: "Gabonaise" },
  { code: "CG", flag: "🇨🇬", label: "Congolaise (RC)" },
  { code: "CD", flag: "🇨🇩", label: "Congolaise (RDC)" },
  { code: "BJ", flag: "🇧🇯", label: "Béninoise" },
  { code: "TG", flag: "🇹🇬", label: "Togolaise" },
  { code: "NE", flag: "🇳🇪", label: "Nigérienne" },
  { code: "MG", flag: "🇲🇬", label: "Malgache" },
  { code: "KM", flag: "🇰🇲", label: "Comorienne" },
  { code: "DJ", flag: "🇩🇯", label: "Djiboutienne" },
  { code: "CF", flag: "🇨🇫", label: "Centrafricaine" },
  { code: "GQ", flag: "🇬🇶", label: "Équato-guinéenne" },
  { code: "MR", flag: "🇲🇷", label: "Mauritanienne" },
  { code: "RW", flag: "🇷🇼", label: "Rwandaise" },
  { code: "BI", flag: "🇧🇮", label: "Burundaise" },
  { code: "DZ", flag: "🇩🇿", label: "Algérienne" },
  { code: "MA", flag: "🇲🇦", label: "Marocaine" },
  { code: "TN", flag: "🇹🇳", label: "Tunisienne" },
  { code: "LY", flag: "🇱🇾", label: "Libyenne" },
  { code: "EG", flag: "🇪🇬", label: "Égyptienne" },
  { code: "NG", flag: "🇳🇬", label: "Nigériane" },
  { code: "GH", flag: "🇬🇭", label: "Ghanéenne" },
  { code: "ET", flag: "🇪🇹", label: "Éthiopienne" },
  { code: "KE", flag: "🇰🇪", label: "Kényane" },
  { code: "TZ", flag: "🇹🇿", label: "Tanzanienne" },
  { code: "UG", flag: "🇺🇬", label: "Ougandaise" },
  { code: "ZA", flag: "🇿🇦", label: "Sud-Africaine" },
  { code: "AO", flag: "🇦🇴", label: "Angolaise" },
  { code: "MZ", flag: "🇲🇿", label: "Mozambicaine" },
  { code: "SC", flag: "🇸🇨", label: "Seychelloise" },
  { code: "MU", flag: "🇲🇺", label: "Mauricienne" },
  { code: "LB", flag: "🇱🇧", label: "Libanaise" },
  { code: "SY", flag: "🇸🇾", label: "Syrienne" },
  { code: "IQ", flag: "🇮🇶", label: "Irakienne" },
  { code: "TR", flag: "🇹🇷", label: "Turque" },
  { code: "IN", flag: "🇮🇳", label: "Indienne" },
  { code: "PK", flag: "🇵🇰", label: "Pakistanaise" },
  { code: "BD", flag: "🇧🇩", label: "Bangladaise" },
  { code: "LK", flag: "🇱🇰", label: "Sri-Lankaise" },
  { code: "CN", flag: "🇨🇳", label: "Chinoise" },
  { code: "PH", flag: "🇵🇭", label: "Philippine" },
  { code: "VN", flag: "🇻🇳", label: "Vietnamienne" },
  { code: "TH", flag: "🇹🇭", label: "Thaïlandaise" },
  { code: "ID", flag: "🇮🇩", label: "Indonésienne" },
  { code: "BR", flag: "🇧🇷", label: "Brésilienne" },
  { code: "CO", flag: "🇨🇴", label: "Colombienne" },
  { code: "MX", flag: "🇲🇽", label: "Mexicaine" },
  { code: "PE", flag: "🇵🇪", label: "Péruvienne" },
  { code: "HT", flag: "🇭🇹", label: "Haïtienne" },
  { code: "DO", flag: "🇩🇴", label: "Dominicaine" },
  { code: "RU", flag: "🇷🇺", label: "Russe" },
  { code: "UA", flag: "🇺🇦", label: "Ukrainienne" },
  { code: "GE", flag: "🇬🇪", label: "Géorgienne" },
  { code: "AM", flag: "🇦🇲", label: "Arménienne" },
  { code: "FR", flag: "🇫🇷", label: "Française" },
  { code: "US", flag: "🇺🇸", label: "Américaine" },
  { code: "GB", flag: "🇬🇧", label: "Britannique" },
  { code: "DE", flag: "🇩🇪", label: "Allemande" },
  { code: "ES", flag: "🇪🇸", label: "Espagnole" },
  { code: "IT", flag: "🇮🇹", label: "Italienne" },
  { code: "PT", flag: "🇵🇹", label: "Portugaise" },
  { code: "BE", flag: "🇧🇪", label: "Belge" },
  { code: "CH", flag: "🇨🇭", label: "Suisse" },
  { code: "CA", flag: "🇨🇦", label: "Canadienne" },
  { code: "JP", flag: "🇯🇵", label: "Japonaise" },
  { code: "KR", flag: "🇰🇷", label: "Sud-Coréenne" },
  { code: "AU", flag: "🇦🇺", label: "Australienne" },
];
